--------------------------------------------------------
--  File created - Sunday-October-31-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADVISOR
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."ADVISOR" 
   (	"STUDENT_ID" NUMBER, 
	"INST_NO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUILDING
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."BUILDING" 
   (	"BUILD_NO" NUMBER, 
	"BUILD_LOC" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLASS_ROOM
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."CLASS_ROOM" 
   (	"CLS_NO" NUMBER, 
	"CAPACITY" NUMBER, 
	"BUILD_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."COURSE" 
   (	"COURSE_ID" NUMBER, 
	"COURSE_TITLE" VARCHAR2(50 BYTE), 
	"DESCREPTION" VARCHAR2(50 BYTE), 
	"DEPT_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."DEPARTMENT" 
   (	"DEPT_NO" NUMBER, 
	"DEPT_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DURATION_TIME
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."DURATION_TIME" 
   (	"DURATION_NO" NUMBER, 
	"DAY_IN_WEEK" VARCHAR2(20 BYTE), 
	"START_DATE" DATE DEFAULT '20-feb-2020', 
	"DURATION_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INSTRUCTOR
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."INSTRUCTOR" 
   (	"INST_NO" NUMBER, 
	"INST_FNAME" VARCHAR2(50 BYTE), 
	"INST_LNAME" VARCHAR2(50 BYTE), 
	"DEPT_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LECTURE_SECTION
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."LECTURE_SECTION" 
   (	"SECT_NO" NUMBER, 
	"SEC_YEAR" VARCHAR2(4 BYTE), 
	"COURSE_NO" NUMBER, 
	"DURATION_NO" NUMBER, 
	"CLS_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREREQ
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."PREREQ" 
   (	"COURSE_ID" NUMBER, 
	"PREREQ_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRIVILLAGES
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."PRIVILLAGES" 
   (	"PRIV_ID" NUMBER, 
	"PRIV_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."STUDENT" 
   (	"STUDENT_ID" NUMBER, 
	"STUDENT_NAME" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"DEPT_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAKE_SECTION
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."TAKE_SECTION" 
   (	"LEC_NO" NUMBER, 
	"COURSE_ID" NUMBER, 
	"SECT_NO" NUMBER, 
	"SEMESTER" CHAR(2 BYTE), 
	"SECT_YEAR" DATE, 
	"GRADE" NUMBER, 
	"STUDENT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEACHES
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."TEACHES" 
   (	"TEACHES_NO" NUMBER, 
	"SECT_NO" NUMBER, 
	"COURSE_ID" NUMBER, 
	"SEMESTER" CHAR(2 BYTE), 
	"TEACH_YEAR" NUMBER(*,0), 
	"INST_NO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"ROLE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS_ROLES
--------------------------------------------------------

  CREATE TABLE "COLLAGE"."USERS_ROLES" 
   (	"ROLE_ID" NUMBER, 
	"ROLE_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into COLLAGE.ADVISOR
SET DEFINE OFF;
REM INSERTING into COLLAGE.BUILDING
SET DEFINE OFF;
Insert into COLLAGE.BUILDING (BUILD_NO,BUILD_LOC) values (1,'alsonaina');
Insert into COLLAGE.BUILDING (BUILD_NO,BUILD_LOC) values (2,null);
Insert into COLLAGE.BUILDING (BUILD_NO,BUILD_LOC) values (3,'Haddah');
REM INSERTING into COLLAGE.CLASS_ROOM
SET DEFINE OFF;
Insert into COLLAGE.CLASS_ROOM (CLS_NO,CAPACITY,BUILD_NO) values (2,70,1);
Insert into COLLAGE.CLASS_ROOM (CLS_NO,CAPACITY,BUILD_NO) values (1,25,1);
Insert into COLLAGE.CLASS_ROOM (CLS_NO,CAPACITY,BUILD_NO) values (3,50,1);
Insert into COLLAGE.CLASS_ROOM (CLS_NO,CAPACITY,BUILD_NO) values (4,35,1);
Insert into COLLAGE.CLASS_ROOM (CLS_NO,CAPACITY,BUILD_NO) values (5,60,1);
Insert into COLLAGE.CLASS_ROOM (CLS_NO,CAPACITY,BUILD_NO) values (6,70,1);
REM INSERTING into COLLAGE.COURSE
SET DEFINE OFF;
Insert into COLLAGE.COURSE (COURSE_ID,COURSE_TITLE,DESCREPTION,DEPT_NO) values (1,'tech','oracle',1);
Insert into COLLAGE.COURSE (COURSE_ID,COURSE_TITLE,DESCREPTION,DEPT_NO) values (3,'"humen resources','humen resource ',1);
Insert into COLLAGE.COURSE (COURSE_ID,COURSE_TITLE,DESCREPTION,DEPT_NO) values (8,'Cyber Security','network',1);
Insert into COLLAGE.COURSE (COURSE_ID,COURSE_TITLE,DESCREPTION,DEPT_NO) values (10,'system development inveronment','analysis and design applications',1);
Insert into COLLAGE.COURSE (COURSE_ID,COURSE_TITLE,DESCREPTION,DEPT_NO) values (5,'DBMS','database management system',2);
REM INSERTING into COLLAGE.DEPARTMENT
SET DEFINE OFF;
Insert into COLLAGE.DEPARTMENT (DEPT_NO,DEPT_NAME) values (1,'accounting');
Insert into COLLAGE.DEPARTMENT (DEPT_NO,DEPT_NAME) values (2,'MIS');
Insert into COLLAGE.DEPARTMENT (DEPT_NO,DEPT_NAME) values (3,'Managment');
Insert into COLLAGE.DEPARTMENT (DEPT_NO,DEPT_NAME) values (4,'Marketing');
REM INSERTING into COLLAGE.DURATION_TIME
SET DEFINE OFF;
Insert into COLLAGE.DURATION_TIME (DURATION_NO,DAY_IN_WEEK,START_DATE,DURATION_TIME) values (1,'2',null,null);
REM INSERTING into COLLAGE.INSTRUCTOR
SET DEFINE OFF;
Insert into COLLAGE.INSTRUCTOR (INST_NO,INST_FNAME,INST_LNAME,DEPT_NO) values (15,'Moneer ','Alkadasy',1);
Insert into COLLAGE.INSTRUCTOR (INST_NO,INST_FNAME,INST_LNAME,DEPT_NO) values (2,'Aisha','alhag',1);
Insert into COLLAGE.INSTRUCTOR (INST_NO,INST_FNAME,INST_LNAME,DEPT_NO) values (3,'Shaima','Azzandany',1);
REM INSERTING into COLLAGE.LECTURE_SECTION
SET DEFINE OFF;
Insert into COLLAGE.LECTURE_SECTION (SECT_NO,SEC_YEAR,COURSE_NO,DURATION_NO,CLS_NO) values (1,null,null,null,null);
Insert into COLLAGE.LECTURE_SECTION (SECT_NO,SEC_YEAR,COURSE_NO,DURATION_NO,CLS_NO) values (2,'2020',1,2,2);
Insert into COLLAGE.LECTURE_SECTION (SECT_NO,SEC_YEAR,COURSE_NO,DURATION_NO,CLS_NO) values (5,'2022',1,4,2);
REM INSERTING into COLLAGE.PREREQ
SET DEFINE OFF;
Insert into COLLAGE.PREREQ (COURSE_ID,PREREQ_NO) values (1,2);
Insert into COLLAGE.PREREQ (COURSE_ID,PREREQ_NO) values (1,4);
Insert into COLLAGE.PREREQ (COURSE_ID,PREREQ_NO) values (5,3);
REM INSERTING into COLLAGE.PRIVILLAGES
SET DEFINE OFF;
REM INSERTING into COLLAGE.STUDENT
SET DEFINE OFF;
Insert into COLLAGE.STUDENT (STUDENT_ID,STUDENT_NAME,PHONE,DEPT_NO) values (1,'jamal','+967776278868',1);
Insert into COLLAGE.STUDENT (STUDENT_ID,STUDENT_NAME,PHONE,DEPT_NO) values (5,'habeeb','+77654',1);
Insert into COLLAGE.STUDENT (STUDENT_ID,STUDENT_NAME,PHONE,DEPT_NO) values (2,'Bashar','+96777543221',1);
Insert into COLLAGE.STUDENT (STUDENT_ID,STUDENT_NAME,PHONE,DEPT_NO) values (3,'Ismaiel','+96777432009',1);
Insert into COLLAGE.STUDENT (STUDENT_ID,STUDENT_NAME,PHONE,DEPT_NO) values (4,'Mohammed','+96777588443',1);
Insert into COLLAGE.STUDENT (STUDENT_ID,STUDENT_NAME,PHONE,DEPT_NO) values (6,'Younes','+967772209887',1);
REM INSERTING into COLLAGE.TAKE_SECTION
SET DEFINE OFF;
REM INSERTING into COLLAGE.TEACHES
SET DEFINE OFF;
REM INSERTING into COLLAGE.USERS
SET DEFINE OFF;
Insert into COLLAGE.USERS (USER_ID,USER_NAME,ROLE_ID) values ('2','user_student_affairs',null);
Insert into COLLAGE.USERS (USER_ID,USER_NAME,ROLE_ID) values ('1','admin',null);
REM INSERTING into COLLAGE.USERS_ROLES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_DEPARTMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_DEPARTMENT" ON "COLLAGE"."DEPARTMENT" ("DEPT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INSTRUCTOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_INSTRUCTOR" ON "COLLAGE"."INSTRUCTOR" ("INST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STUDENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_STUDENT" ON "COLLAGE"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CLASS_ROOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_CLASS_ROOM" ON "COLLAGE"."CLASS_ROOM" ("CLS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PREREQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_PREREQ" ON "COLLAGE"."PREREQ" ("PREREQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SECTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_SECTION" ON "COLLAGE"."LECTURE_SECTION" ("SECT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_COURSE
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_COURSE" ON "COLLAGE"."COURSE" ("COURSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LECTURE
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_LECTURE" ON "COLLAGE"."TAKE_SECTION" ("LEC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_ROLES" ON "COLLAGE"."USERS_ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_USER" ON "COLLAGE"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BUILDING
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_BUILDING" ON "COLLAGE"."BUILDING" ("BUILD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DURATION_TIME
--------------------------------------------------------

  CREATE UNIQUE INDEX "COLLAGE"."PK_DURATION_TIME" ON "COLLAGE"."DURATION_TIME" ("DURATION_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DURATION_TIME
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."DURATION_TIME" ADD CONSTRAINT "PK_DURATION_TIME" PRIMARY KEY ("DURATION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."INSTRUCTOR" ADD CONSTRAINT "PK_INSTRUCTOR" PRIMARY KEY ("INST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."USERS" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LECTURE_SECTION
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."LECTURE_SECTION" ADD CONSTRAINT "PK_SECTION" PRIMARY KEY ("SECT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUILDING
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."BUILDING" ADD CONSTRAINT "PK_BUILDING" PRIMARY KEY ("BUILD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."STUDENT" ADD CONSTRAINT "PK_STUDENT" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAKE_SECTION
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."TAKE_SECTION" ADD CONSTRAINT "PK_LECTURE" PRIMARY KEY ("LEC_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREREQ
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."PREREQ" ADD CONSTRAINT "PK_PREREQ" PRIMARY KEY ("PREREQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS_ROLES
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."USERS_ROLES" ADD CONSTRAINT "PK_ROLES" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLASS_ROOM
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."CLASS_ROOM" ADD CONSTRAINT "PK_CLASS_ROOM" PRIMARY KEY ("CLS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY ("DEPT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."COURSE" ADD CONSTRAINT "PK_COURSE" PRIMARY KEY ("COURSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADVISOR
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."ADVISOR" ADD CONSTRAINT "FK_ADVISOR_INST_NO" FOREIGN KEY ("INST_NO")
	  REFERENCES "COLLAGE"."INSTRUCTOR" ("INST_NO") ENABLE;
 
  ALTER TABLE "COLLAGE"."ADVISOR" ADD CONSTRAINT "FK_ADVISOR_STUDENT_NO" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "COLLAGE"."STUDENT" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLASS_ROOM
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."CLASS_ROOM" ADD CONSTRAINT "FK_CLASS_ROOM_BUILDING" FOREIGN KEY ("BUILD_NO")
	  REFERENCES "COLLAGE"."BUILDING" ("BUILD_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."COURSE" ADD CONSTRAINT "FK_COURSE_DEPT_NO" FOREIGN KEY ("DEPT_NO")
	  REFERENCES "COLLAGE"."DEPARTMENT" ("DEPT_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."INSTRUCTOR" ADD CONSTRAINT "FK_INSTRUCTOR_DEPT_NO" FOREIGN KEY ("DEPT_NO")
	  REFERENCES "COLLAGE"."DEPARTMENT" ("DEPT_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LECTURE_SECTION
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."LECTURE_SECTION" ADD CONSTRAINT "FK_SECTION_CLS_NO" FOREIGN KEY ("CLS_NO")
	  REFERENCES "COLLAGE"."CLASS_ROOM" ("CLS_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREREQ
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."PREREQ" ADD CONSTRAINT "FK_PREREQ_COURSE_ID" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "COLLAGE"."COURSE" ("COURSE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."STUDENT" ADD CONSTRAINT "FK_STUDENT_DEPT_NO" FOREIGN KEY ("DEPT_NO")
	  REFERENCES "COLLAGE"."DEPARTMENT" ("DEPT_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAKE_SECTION
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."TAKE_SECTION" ADD CONSTRAINT "FK_LECTURE_COURSE_NO" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "COLLAGE"."COURSE" ("COURSE_ID") ENABLE;
 
  ALTER TABLE "COLLAGE"."TAKE_SECTION" ADD CONSTRAINT "FK_LECTURE_SEC_NO" FOREIGN KEY ("SECT_NO")
	  REFERENCES "COLLAGE"."LECTURE_SECTION" ("SECT_NO") ENABLE;
 
  ALTER TABLE "COLLAGE"."TAKE_SECTION" ADD CONSTRAINT "TAKE_SECTION_STUDENT_NO" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "COLLAGE"."STUDENT" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEACHES
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."TEACHES" ADD CONSTRAINT "FK_TEACHES_COURSE_ID" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "COLLAGE"."COURSE" ("COURSE_ID") ENABLE;
 
  ALTER TABLE "COLLAGE"."TEACHES" ADD CONSTRAINT "FK_TEACHES_SECT_NO" FOREIGN KEY ("SECT_NO")
	  REFERENCES "COLLAGE"."LECTURE_SECTION" ("SECT_NO") ENABLE;
 
  ALTER TABLE "COLLAGE"."TEACHES" ADD CONSTRAINT "PK_TEACHES" FOREIGN KEY ("INST_NO")
	  REFERENCES "COLLAGE"."INSTRUCTOR" ("INST_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "COLLAGE"."USERS" ADD CONSTRAINT "FK_USERS_ROLE_ID" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "COLLAGE"."USERS_ROLES" ("ROLE_ID") ENABLE;
